import{i as n,S as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l=document.querySelector(".search-form"),u=document.querySelector(".search-input"),f=document.querySelector(".gallery"),m="43275871-c76d4a7895f35b3cf58095282";l.addEventListener("submit",d);function d(s){s.preventDefault();const o=u.value.trim();if(o===""){n.error({title:"Error",message:"Please enter a search images",position:"topRight"});return}const i=new URLSearchParams({key:m,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});fetch(`https://pixabay.com/api?${i}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>f.insertAdjacentHTML("beforeend",h(r.hits))).catch(r=>{data.hits.length===0&&n.error({title:"Error",message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight"})})}function h(s){return s.map(({webformatURL:o,largeImageURL:i,tags:r,id:e,likes:t,views:a,comments:p,downloads:y})=>`
    <li class="gallery-item" data-id = ${e}>
        <a class="gallery-link" href="${i}">
            <img
                class="gallery-image"
                src="${o}"
                alt="${r}" />
        </a>
    </li>`).join("")}new c("gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
